### ISSUE TITLE
Form submits to / (instead of /api/accounts/new)

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid-contrib/solid-signup-ui#20]
I updated the signup app on databox2 to the most recent `gh-pages` as of this morning.
Filled out all the fields, hit submit - the form posts to `/` instead of the expected `/api/accounts/new`.
The config lines at the top of the .js file seem to be correct:

``` js
  var DOMAIN = 'https://databox2.com'
  var SIGNIN_LINK = 'https://databox2.com/signin/'
  var ACCOUNT_ENDPOINT = 'api/accounts/new'
```

(Also, the browser's JS console has 8 warnings of:
`Empty string passed to getElementById().` 
in case that's relevant.

What am I missing?

**Comment by gbaudusseau** [comment]
Are you using this page http://solid.github.io/solid-signup-ui/signup/ ?

it is not  http://solid.github.io/solid-signup-ui/ (that one not ready yet)

**Comment by dmitrizagidulin** [comment]
I'm using this page: https://databox2.com/

**Comment by gbaudusseau** [comment]
use https://databox2.com/signup/

**Comment by dmitrizagidulin** [comment]
Got it, that seems to post to the right location. Closing. Thanks! :)
